name: "Run Tests - Current"

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        php: [8.0,8.1,8.2]
        dependency-version: [prefer-lowest, prefer-stable]

    name: P${{ matrix.php }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-${{ matrix.dependency-version }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring, pdo, sqlite, pdo_sqlite, iconv
          coverage: none

      - name: Install dependencies
        run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction -W

      - name: Execute tests
        run: vendor/bin/phpunit
